/* =========================================================
 * 贝加尔湖畔 · 游戏数据（TNO 融合版）
 * 融合素材：
 * - 原著小说《贝加尔湖畔》
 * - TNO: The New Order 正史（布里亚特ASSR/萨布林/亚戈达）
 * - TNO 子模组「东方红 The East is Red」（西北中共线）
 * - TNO 子模组「2WRW 第二次西俄战争」（1971 统一俄罗斯对德战争）
 * - 「贝加尔湖之光 Light From Lake Baikal」（中国旅回国线）
 * =======================================================*/

// ===== 角色数据库 =====
const Characters = {
  // ---- 主角团 ----
  anna: {
    id: 'anna',
    name: '安娜·罗森塔尔娃',
    shortName: '安娜',
    role: '地下宣传员',
    povTitle: '视角：安娜·罗森塔尔娃',
    avatar: '🎹',
    color: '#d4a5e0',
    desc: '犹太裔女孩，1943年生于斯摩棱斯克，随父亲一路东逃至贝加尔湖畔。三年前被一名年轻海军士官从NKVD手中救下，现于上乌金斯克干部俱乐部工作，秘密参加地下布尔什维克组织。',
    stats: { hp: 80, atk: 8, def: 4, spd: 12, mp: 50 },
    skills: ['国际歌', '宣传鼓动', '医疗急救'],
  },
  sablin: {
    id: 'sablin',
    name: '瓦列里·萨布林',
    shortName: '萨布林',
    role: '布里亚特革命领袖',
    povTitle: '视角：瓦列里·萨布林',
    avatar: '⭐',
    color: '#e8c870',
    desc: '1939年生，年仅23岁的青年政委。生于列宁格勒，长于乌兰乌德，没有卫国战争的记忆，却从小梦想着记忆里的那个苏联。曾在亚戈达军中服役，中西伯利亚战争后理想破灭，决意发动「新十月革命」。',
    stats: { hp: 120, atk: 18, def: 10, spd: 14, mp: 80 },
    skills: ['革命号召', '战术指挥', '政治工作'],
  },
  efim: {
    id: 'efim',
    name: '叶菲姆·格拉西莫夫',
    shortName: '叶菲姆',
    role: '青年工人',
    povTitle: '视角：叶菲姆·格拉西莫夫',
    avatar: '🔧',
    color: '#a0d0a0',
    desc: '十六岁的青年工人，父亲死于对德战争，母亲死于肺结核。在干部俱乐部仓库做工，对安娜抱有朦胧的好感。后来成为红军最年轻的机枪手。',
    stats: { hp: 70, atk: 10, def: 5, spd: 10, mp: 30 },
    skills: ['体力劳作', '修理机械', '勇敢冲锋'],
  },
  lyupasha: {
    id: 'lyupasha',
    name: '柳帕莎·罗曼诺娃',
    shortName: '柳帕莎',
    role: '西岸负责人',
    povTitle: '视角：柳帕莎·罗曼诺娃',
    avatar: '🌹',
    color: '#e090a0',
    desc: '西岸总部负责人，曾任亚戈达的机要秘书，借职务之便为组织输送情报。姓氏暗示与旧皇室渊源颇深，但她选择了革命的道路。',
    stats: { hp: 90, atk: 12, def: 8, spd: 16, mp: 60 },
    skills: ['情报收集', '伪装渗透', '精密射击'],
  },

  // ---- 布里亚特 ASSR 领导层（TNO 正史） ----
  andrei: {
    id: 'andrei',
    name: '安德烈·托尔斯泰',
    shortName: '老安德烈',
    role: '东岸负责人',
    avatar: '👴',
    color: '#b0a080',
    desc: '东岸总部负责人，经历过旧时代的老布尔什维克。人称「老安德烈」，务实而坚韧，像西伯利亚的落叶松一样扎根冻土。',
    stats: { hp: 100, atk: 14, def: 12, spd: 8, mp: 70 },
    skills: ['经验之谈', '稳定军心', '老式步枪'],
  },
  valentina: {
    id: 'valentina',
    name: '瓦伦蒂娜·娜塔莉亚诺娃',
    shortName: '瓦伦蒂娜',
    role: '青年代表',
    avatar: '💫',
    color: '#90c0e0',
    desc: '十六岁的少女，声音如银铃般清脆。活跃于青年运动一线，是组织内最年轻的骨干之一，负责大会主持与联络工作。',
    stats: { hp: 65, atk: 6, def: 3, spd: 18, mp: 80 },
    skills: ['青春活力', '动员演讲', '敏捷闪避'],
  },
  pechuro: {
    id: 'pechuro',
    name: '苏珊娜·佩楚罗',
    shortName: '佩楚罗',
    role: '政府首脑',
    avatar: '📚',
    color: '#c0a0e0',
    desc: '布里亚特ASSR政府首脑，坚定的共产主义老战士。生于1929年，青年时代因反抗案入狱，在劳改营中度过十年。她将是新苏联的第一任部长会议主席。',
    stats: { hp: 85, atk: 10, def: 8, spd: 11, mp: 75 },
    skills: ['组织建设', '群众路线', '坚毅抵抗'],
  },
  braun: {
    id: 'braun',
    name: '奥托·布劳恩',
    shortName: '布劳恩',
    role: '外交部长',
    avatar: '🌍',
    color: '#a0b0c0',
    desc: '德国共产党人，即当年那位远东顾问「李德」。纳粹上台后流亡苏联二十年，如今在贝加尔湖畔为萨布林执掌外交。他坚信：不是所有德国人都是敌人。',
    stats: { hp: 75, atk: 9, def: 7, spd: 9, mp: 70 },
    skills: ['外交斡旋', '国际主义', '德语广播'],
  },
  ulanovskaya: {
    id: 'ulanovskaya',
    name: '玛雅·乌拉诺夫斯卡娅',
    shortName: '玛雅',
    role: '经济部长',
    avatar: '📊',
    color: '#90d0c0',
    desc: '经济部长，曾在劳改营中度过八年青春。她掌管着布里亚特计划经济的每一颗螺丝钉，深知「面包与自由必须兼得」。',
    stats: { hp: 70, atk: 8, def: 6, spd: 12, mp: 65 },
    skills: ['计划统筹', '增产节约', '后勤调度'],
  },

  // ---- 敌方 ----
  yagoda: {
    id: 'yagoda',
    name: '亨利希·亚戈达',
    shortName: '亚戈达',
    role: '「最高主席团」主席',
    avatar: '👹',
    color: '#804040',
    desc: '前内务人民委员部首脑，自封「苏联最高主席团」主席。西俄战争失败后龟缩贝加尔湖畔，把这片土地变成了全俄最腐败最肮脏的地方。他的「苏联」早已死了。',
    stats: { hp: 200, atk: 20, def: 15, spd: 10, mp: 100 },
    skills: ['NKVD镇压', '特务统治', '最后挣扎'],
    isBoss: true,
  },
  nkvd_officer: {
    id: 'nkvd_officer',
    name: 'NKVD军官',
    shortName: 'NKVD军官',
    role: '内务军官',
    avatar: '👮',
    color: '#606070',
    desc: '亚戈达的打手，在贝加尔湖畔横征暴敛、为非作歹。三年前曾欲对安娜行不轨，被一名年轻海军士官阻止。',
    stats: { hp: 60, atk: 12, def: 6, spd: 8, mp: 20 },
    skills: ['棍棒殴打', '恐吓威胁'],
  },
  nkvd_soldier: {
    id: 'nkvd_soldier',
    name: 'NKVD士兵',
    shortName: 'NKVD士兵',
    role: '内务部队',
    avatar: '💂',
    color: '#505060',
    desc: '内务人民委员部的普通士兵，大多是被强征的青年。装备参差不齐，士气低落——他们中的许多人正在等待倒戈的机会。',
    stats: { hp: 40, atk: 8, def: 4, spd: 7, mp: 10 },
    skills: ['步枪齐射', '刺刀冲锋'],
  },
  nkvd_captain: {
    id: 'nkvd_captain',
    name: 'NKVD纠察队长',
    shortName: 'NKVD队长',
    role: '纠察队长',
    avatar: '🎖️',
    color: '#705050',
    desc: 'NKVD纠察队队长，经验丰富的特务头子。嗅觉灵敏，手段狠辣，率队突袭地下大会。',
    stats: { hp: 100, atk: 16, def: 10, spd: 11, mp: 40 },
    skills: ['指挥冲锋', '手枪速射', '呼叫增援'],
  },
  german_soldier: {
    id: 'german_soldier',
    name: '德军东方专员辖士兵',
    shortName: '德军士兵',
    role: '占领军',
    avatar: '⚙',
    color: '#707080',
    desc: '纳粹德国东方专员辖区（莫斯科维亚）的驻防士兵。装备精良，但士气已被漫长的游击战消磨殆尽。',
    stats: { hp: 65, atk: 15, def: 9, spd: 9, mp: 20 },
    skills: ['StG突击步枪', '铁拳反坦克', ' MG机枪压制'],
  },
  japanese_soldier: {
    id: 'japanese_soldier',
    name: '关东军士兵',
    shortName: '关东军',
    role: '占领军',
    avatar: '🎌',
    color: '#a06060',
    desc: '日本关东军的士兵，隔着满洲国境虎视眈眈。据说西北的中国共产党正在酝酿总反攻——他们的日子也不多了。',
    stats: { hp: 55, atk: 13, def: 7, spd: 9, mp: 20 },
    skills: ['三八式步枪', '万岁冲锋'],
  },
  ss_officer: {
    id: 'ss_officer',
    name: '武装党卫军军官',
    shortName: '党卫军',
    role: '党卫军',
    avatar: '💀',
    color: '#404050',
    desc: '日耳曼尼亚最后狂热者。施佩尔政府风雨飘摇之际，只有他们还相信「新秩序」能赢下最后一战。',
    stats: { hp: 110, atk: 18, def: 12, spd: 10, mp: 40 },
    skills: ['狂热冲锋', '装甲铁拳', '最后防御'],
  },
};

// ===== 技能数据库 =====
const Skills = {
  '国际歌': { type: 'buff', desc: '激昂的歌声鼓舞士气，提升全队攻击力', mp: 20, effect: { atkBoost: 0.3, duration: 3 }, target: 'ally_all' },
  '宣传鼓动': { type: 'debuff', desc: '揭露敌人的暴行，降低敌人士气', mp: 15, effect: { atkDrop: 0.2, duration: 2 }, target: 'enemy_all' },
  '医疗急救': { type: 'heal', desc: '简单的急救处理，恢复单体HP', mp: 25, effect: { heal: 40 }, target: 'ally_single' },
  '革命号召': { type: 'buff', desc: '振奋人心的演讲，大幅提升全队属性', mp: 35, effect: { atkBoost: 0.5, defBoost: 0.3, duration: 4 }, target: 'ally_all' },
  '战术指挥': { type: 'special', desc: '下达战术指令，下一次攻击必定暴击', mp: 20, effect: { crit: true }, target: 'ally_single' },
  '政治工作': { type: 'debuff', desc: '对敌喊话，有几率使敌人投诚（跳过回合）', mp: 30, effect: { charm: 0.3 }, target: 'enemy_single' },
  '体力劳作': { type: 'attack', desc: '凭借体力发起猛攻', mp: 0, effect: { dmgMul: 1.2 }, target: 'enemy_single' },
  '修理机械': { type: 'heal', desc: '熟练的手艺，修复装备恢复少量HP', mp: 10, effect: { heal: 20 }, target: 'ally_single' },
  '勇敢冲锋': { type: 'attack', desc: '无所畏惧地冲向敌人，伤害提升但防御下降', mp: 10, effect: { dmgMul: 1.5, selfDefDrop: 0.3 }, target: 'enemy_single' },
  '情报收集': { type: 'debuff', desc: '分析敌人弱点，下次攻击必定命中且暴击', mp: 20, effect: { expose: true }, target: 'enemy_single' },
  '伪装渗透': { type: 'special', desc: '巧妙伪装，使自身闪避率大幅提升', mp: 25, effect: { dodge: 0.6, duration: 2 }, target: 'self' },
  '精密射击': { type: 'attack', desc: '精准的一枪，高伤害高暴击', mp: 20, effect: { dmgMul: 1.8, critBonus: 0.3 }, target: 'enemy_single' },
  '经验之谈': { type: 'buff', desc: '老一辈的经验，提升全队防御', mp: 20, effect: { defBoost: 0.4, duration: 3 }, target: 'ally_all' },
  '稳定军心': { type: 'heal', desc: '沉稳的话语安定军心，恢复全体少量HP', mp: 30, effect: { heal: 25 }, target: 'ally_all' },
  '老式步枪': { type: 'attack', desc: '用老式步枪精确射击', mp: 5, effect: { dmgMul: 1.4 }, target: 'enemy_single' },
  '青春活力': { type: 'buff', desc: '青春的能量，提升全队速度', mp: 15, effect: { spdBoost: 0.5, duration: 3 }, target: 'ally_all' },
  '动员演讲': { type: 'special', desc: '激情演讲，恢复队伍士气（MP）', mp: 0, effect: { mpRestore: 15 }, target: 'ally_all' },
  '敏捷闪避': { type: 'passive', desc: '天生敏捷，闪避率较高', mp: 0, effect: { dodge: 0.15 }, target: 'self' },
  // 布里亚特领导层技能
  '组织建设': { type: 'buff', desc: '重建党的组织，全队防御与攻击提升', mp: 30, effect: { atkBoost: 0.25, defBoost: 0.35, duration: 3 }, target: 'ally_all' },
  '群众路线': { type: 'heal', desc: '发动群众支前，全队恢复HP', mp: 25, effect: { heal: 30 }, target: 'ally_all' },
  '坚毅抵抗': { type: 'buff', desc: '劳改营岁月锤炼出的意志，大幅提升自身防御', mp: 15, effect: { defBoost: 0.8, duration: 3 }, target: 'self' },
  '外交斡旋': { type: 'debuff', desc: '分化敌方阵营，降低敌方全体攻击', mp: 25, effect: { atkDrop: 0.25, duration: 3 }, target: 'enemy_all' },
  '国际主义': { type: 'buff', desc: '全世界无产者联合起来！全队大幅增益', mp: 40, effect: { atkBoost: 0.4, defBoost: 0.4, spdBoost: 0.3, duration: 4 }, target: 'ally_all' },
  '德语广播': { type: 'debuff', desc: '用德语向敌军喊话——德国也有过台尔曼同志', mp: 30, effect: { charm: 0.4 }, target: 'enemy_single' },
  '计划统筹': { type: 'buff', desc: '精密的计划安排，全队速度与攻击提升', mp: 25, effect: { spdBoost: 0.4, atkBoost: 0.2, duration: 3 }, target: 'ally_all' },
  '增产节约': { type: 'special', desc: '节约资源，恢复全队MP', mp: 0, effect: { mpRestore: 20 }, target: 'ally_all' },
  '后勤调度': { type: 'heal', desc: '后勤补给的奇迹，全队大幅恢复HP', mp: 35, effect: { heal: 45 }, target: 'ally_all' },
  // 敌方技能
  '棍棒殴打': { type: 'attack', desc: '用警棍殴打', mp: 0, effect: { dmgMul: 1.0 }, target: 'enemy_single' },
  '恐吓威胁': { type: 'debuff', desc: '凶狠的威胁降低敌人士气', mp: 10, effect: { atkDrop: 0.2, duration: 2 }, target: 'enemy_single' },
  '步枪齐射': { type: 'attack', desc: '步枪射击', mp: 0, effect: { dmgMul: 1.1 }, target: 'enemy_single' },
  '刺刀冲锋': { type: 'attack', desc: '端起刺刀冲上来', mp: 5, effect: { dmgMul: 1.3 }, target: 'enemy_single' },
  '指挥冲锋': { type: 'buff', desc: '命令部下冲锋，提升敌方攻击', mp: 20, effect: { atkBoost: 0.3, duration: 2 }, target: 'ally_all' },
  '手枪速射': { type: 'attack', desc: '快速连开数枪', mp: 15, effect: { dmgMul: 1.6, hits: 2 }, target: 'enemy_single' },
  '呼叫增援': { type: 'special', desc: '呼叫增援部队', mp: 30, effect: { summon: 'nkvd_soldier' }, target: 'self' },
  'StG突击步枪': { type: 'attack', desc: '纳粹新型突击步枪扫射', mp: 5, effect: { dmgMul: 1.5 }, target: 'enemy_single' },
  '铁拳反坦克': { type: 'attack', desc: '「铁拳」火箭筒轰击', mp: 15, effect: { dmgMul: 1.9 }, target: 'enemy_single' },
  ' MG机枪压制': { type: 'attack', desc: 'MG机枪火力压制全体', mp: 20, effect: { dmgMul: 0.9 }, target: 'enemy_all' },
  '三八式步枪': { type: 'attack', desc: '精准的步枪射击', mp: 0, effect: { dmgMul: 1.2 }, target: 'enemy_single' },
  '万岁冲锋': { type: 'attack', desc: '疯狂的冲锋，伤害很高但自己也会受伤', mp: 10, effect: { dmgMul: 1.8, recoil: 0.2 }, target: 'enemy_single' },
  '狂热冲锋': { type: 'attack', desc: '意识形态狂热的亡命突击', mp: 10, effect: { dmgMul: 1.7, recoil: 0.15 }, target: 'enemy_single' },
  '装甲铁拳': { type: 'attack', desc: '装甲掷弹兵的毁灭一击', mp: 20, effect: { dmgMul: 2.0 }, target: 'enemy_single' },
  '最后防御': { type: 'buff', desc: '「新秩序」的最后防线', mp: 25, effect: { defBoost: 0.7, duration: 2 }, target: 'self' },
  'NKVD镇压': { type: 'attack', desc: '调动全部力量进行镇压', mp: 30, effect: { dmgMul: 1.5 }, target: 'enemy_all' },
  '特务统治': { type: 'debuff', desc: '特务无处不在，降低全军属性', mp: 25, effect: { atkDrop: 0.2, defDrop: 0.2, duration: 3 }, target: 'enemy_all' },
  '最后挣扎': { type: 'buff', desc: '濒死时的疯狂反扑', mp: 40, effect: { atkBoost: 0.8, defDrop: 0.3, duration: 5 }, target: 'self' },
};

// ===== 任务数据库 =====
const Quests = {
  // 序章（TNO 世界观）
  q_tno_intro: {
    id: 'q_tno_intro',
    title: '新秩序的世界',
    desc: '1945年苏联崩溃，1962年纳粹的铁蹄仍在践踏欧亚。了解这个世界的真相。',
    type: 'main',
    chapter: 0,
    objective: '见证 1962 年的世界',
  },
  // 第一章 · 安娜（小说）
  q_tune_piano: {
    id: 'q_tune_piano',
    title: '修理旧钢琴',
    desc: '地下50米的防空洞里，老安德烈搬来一架旧钢琴，交给安娜调音。周五的大会上要用。',
    type: 'main',
    chapter: 1,
    objective: '为钢琴调好音',
  },
  q_club_work: {
    id: 'q_club_work',
    title: '干部俱乐部的日常',
    desc: '在干部俱乐部仓库工作，清点物资。小心那些醉醺醺的NKVD军官。',
    type: 'main',
    chapter: 1,
    objective: '完成今天的工作',
  },
  q_invite_efim: {
    id: 'q_invite_efim',
    title: '邀请叶菲姆',
    desc: '叶菲姆是个好小伙，邀请他参加今晚的组织聚会吧。',
    type: 'side',
    chapter: 1,
    objective: '说服叶菲姆参加聚会',
  },
  // 第二章 · 大会与突袭
  q_meeting: {
    id: 'q_meeting',
    title: '第一次代表大会',
    desc: '地下组织的第一次代表大会即将召开，前往上乌金斯克郊外的防空洞。',
    type: 'main',
    chapter: 2,
    objective: '参加组织大会',
  },
  q_meet_sablin: {
    id: 'q_meet_sablin',
    title: '重逢',
    desc: '萨布林同志也来了……那个三年前救了你的人。',
    type: 'main',
    chapter: 2,
    objective: '与萨布林重逢',
  },
  q_kvkd_raid: {
    id: 'q_kvkd_raid',
    title: 'NKVD突袭',
    desc: 'NKVD纠察队发现了大会地点，必须保护同志们撤离！',
    type: 'main',
    chapter: 2,
    objective: '击退NKVD纠察队',
  },
  // 第三章 · 新十月革命（TNO 正史：广播塔起义）
  q_radio_tower: {
    id: 'q_radio_tower',
    title: '新十月革命',
    desc: '时机成熟了。萨布林将带兵占领上乌金斯克广播塔，向全俄人民广播革命的理想！',
    type: 'main',
    chapter: 3,
    objective: '占领广播塔',
  },
  q_buryatia_founded: {
    id: 'q_buryatia_founded',
    title: '布里亚特 ASSR 成立',
    desc: '革命成功后，组建新政府——佩楚罗、布劳恩、乌拉诺夫斯卡娅各司其职。',
    type: 'main',
    chapter: 3,
    objective: '见证布里亚特ASSR的成立',
  },
  // 第四章 · 解放伊尔库茨克
  q_irkutsk_offensive: {
    id: 'q_irkutsk_offensive',
    title: '伊尔库茨克攻势',
    desc: '向亚戈达的老巢进军！布哈林主义者、布里亚特人、青年军官、妇女——全体人民都在等待这一刻。',
    type: 'main',
    chapter: 4,
    objective: '解放伊尔库茨克',
  },
  // 第五章 · 东方红（联动）
  q_east_red: {
    id: 'q_east_red',
    title: '东方红',
    desc: '西北的中国共产党正在酝酿总反攻。白求恩的医疗队、中国的革命者——全世界无产者联合起来！',
    type: 'main',
    chapter: 5,
    objective: '与中国同志会师',
  },
  // 终章 · 第二次西俄战争
  q_unification: {
    id: 'q_unification',
    title: '统一俄罗斯',
    desc: '从贝加尔湖到乌拉尔，从西伯利亚到波罗的海——再造红军，再造苏维埃，再造苏联！',
    type: 'main',
    chapter: 6,
    objective: '在战略地图上统一俄罗斯',
  },
  q_2wrw: {
    id: 'q_2wrw',
    title: '第二次西俄战争',
    desc: '1971年，俄罗斯复兴。向德国宣战——收复莫斯科，解放全俄罗斯！',
    type: 'main',
    chapter: 7,
    objective: '收复莫斯科，进军日耳曼尼亚',
  },
};

// ===== 战斗场景 =====
const Battles = {
  battle_nkvd_raid: {
    id: 'battle_nkvd_raid',
    name: 'NKVD突袭',
    background: 'bunker',
    description: 'NKVD纠察队冲进了地下会场！保护同志们撤离！',
    enemies: [
      { id: 'nkvd_captain_1', base: 'nkvd_captain', level: 2 },
      { id: 'nkvd_soldier_1', base: 'nkvd_soldier', level: 1 },
      { id: 'nkvd_soldier_2', base: 'nkvd_soldier', level: 1 },
    ],
    reward: { exp: 60, supplies: 20, morale: 10 },
  },
  battle_radio_tower: {
    id: 'battle_radio_tower',
    name: '广播塔之战',
    background: 'radio',
    description: '新十月革命！占领广播塔，向全俄罗斯广播自由的声音！',
    enemies: [
      { id: 'nkvd_officer_1', base: 'nkvd_officer', level: 3 },
      { id: 'nkvd_soldier_1', base: 'nkvd_soldier', level: 2 },
      { id: 'nkvd_soldier_2', base: 'nkvd_soldier', level: 2 },
      { id: 'nkvd_soldier_3', base: 'nkvd_soldier', level: 2 },
    ],
    reward: { exp: 120, supplies: 50, morale: 30 },
  },
  battle_irkutsk: {
    id: 'battle_irkutsk',
    name: '解放伊尔库茨克',
    background: 'irkutsk',
    description: '总攻！亚戈达的克里姆林就在眼前——终结他的「苏联」！',
    enemies: [
      { id: 'yagoda', base: 'yagoda', level: 5 },
      { id: 'nkvd_captain_1', base: 'nkvd_captain', level: 4 },
      { id: 'nkvd_officer_1', base: 'nkvd_officer', level: 3 },
      { id: 'nkvd_soldier_1', base: 'nkvd_soldier', level: 3 },
    ],
    reward: { exp: 300, supplies: 200, morale: 100 },
    isBoss: true,
  },
  battle_moscow: {
    id: 'battle_moscow',
    name: '莫斯科战役',
    background: 'moscow',
    description: '第二次西俄战争！从纳粹手中收复故都莫斯科！',
    enemies: [
      { id: 'ss_officer_1', base: 'ss_officer', level: 6 },
      { id: 'german_1', base: 'german_soldier', level: 5 },
      { id: 'german_2', base: 'german_soldier', level: 5 },
      { id: 'german_3', base: 'german_soldier', level: 4 },
    ],
    reward: { exp: 500, supplies: 400, morale: 100 },
    isBoss: true,
  },
  battle_germania: {
    id: 'battle_germania',
    name: '进军日耳曼尼亚',
    background: 'germania',
    description: '最后一战！红旗将在日耳曼尼亚上空升起——全世界无产者，联合起来！',
    enemies: [
      { id: 'ss_officer_1', base: 'ss_officer', level: 8 },
      { id: 'ss_officer_2', base: 'ss_officer', level: 7 },
      { id: 'german_1', base: 'german_soldier', level: 6 },
      { id: 'german_2', base: 'german_soldier', level: 6 },
      { id: 'german_3', base: 'german_soldier', level: 5 },
    ],
    reward: { exp: 1000, supplies: 1000, morale: 100 },
    isBoss: true,
    isFinal: true,
  },
};

// ===== 战略据点（TNO 俄罗斯军阀地图 + 2WRW 延伸） =====
const Strongholds = {
  // 布里亚特（起点）
  verkhneudinsk: {
    id: 'verkhneudinsk',
    name: '上乌金斯克',
    x: 560, y: 330,
    owner: 'red',
    garrison: 300,
    supplies: 150,
    morale: 90,
    desc: '布里亚特ASSR首都。萨布林的新十月革命从这里开始，广播塔的红色电波传遍全俄。',
  },
  // 伊尔库茨克
  irkutsk: {
    id: 'irkutsk',
    name: '伊尔库茨克',
    x: 430, y: 280,
    owner: 'nkvd',
    garrison: 900,
    supplies: 300,
    morale: 55,
    desc: '亚戈达「最高主席团」的巢穴。NKVD的蓝帽子在这里横行霸道，人民在冰层下等待着春天。',
  },
  // 外贝加尔公国（TNO：Transbaikal Principality 封建政权）
  chita: {
    id: 'chita',
    name: '赤塔「外贝加尔公国」',
    x: 470, y: 380,
    owner: 'feudal',
    garrison: 500,
    supplies: 180,
    morale: 60,
    desc: '被拥戴封建制的白军残余推翻后建立的「公国」。农奴制的幽灵在草原上游荡。',
  },
  // 萨哈（雅库特）
  yakutsk: {
    id: 'yakutsk',
    name: '雅库茨克',
    x: 700, y: 160,
    owner: 'feudal',
    garrison: 350,
    supplies: 120,
    morale: 55,
    desc: '遥远的北方城市，萨哈共和国的冻土领地。',
  },
  // 远东（日本势力范围）
  khabarovsk: {
    id: 'khabarovsk',
    name: '哈巴罗夫斯克',
    x: 790, y: 400,
    owner: 'japan',
    garrison: 600,
    supplies: 250,
    morale: 70,
    desc: '日本帝国势力范围的边境城市，关东军虎视眈眈。传说西北的中国共产党正在酝酿总反攻。',
  },
  // 阿穆尔/马加丹方向
  magadan: {
    id: 'magadan',
    name: '马加丹',
    x: 830, y: 180,
    owner: 'black',
    garrison: 400,
    supplies: 150,
    morale: 65,
    desc: '远东黑军的据点，无政府主义者在冻原上建立的地方。',
  },
  // 新西伯利亚（2WRW 主角舒克申）
  novosibirsk: {
    id: 'novosibirsk',
    name: '新西伯利亚',
    x: 380, y: 220,
    owner: 'siberia',
    garrison: 700,
    supplies: 350,
    morale: 75,
    desc: '西伯利亚联邦的心脏，科学家城与工厂群。「新西伯利亚学派」的知识分子们也在思考俄罗斯的未来。',
  },
  // 鄂木斯克（TNO：黑军团）
  omsk: {
    id: 'omsk',
    name: '鄂木斯克',
    x: 300, y: 180,
    owner: 'black',
    garrison: 550,
    supplies: 200,
    morale: 70,
    desc: '「黑军团」的要塞。他们只想着一件事——以最彻底的暴力报复德国。',
  },
  // 斯维尔德洛夫斯克（巴托夫元帅）
  sverdlovsk: {
    id: 'sverdlovsk',
    name: '斯维尔德洛夫斯克',
    x: 230, y: 150,
    owner: 'siberia',
    garrison: 600,
    supplies: 280,
    morale: 72,
    desc: '巴托夫元帅的乌拉尔堡垒，红军老兵的家园。',
  },
  // 莫斯科（德占东方专员辖区）
  moscow: {
    id: 'moscow',
    name: '莫斯科（德占）',
    x: 130, y: 110,
    owner: 'germany',
    garrison: 2000,
    supplies: 1000,
    morale: 80,
    desc: '「东方专员辖区」首府。纳粹的铁十字悬挂在克里姆林宫上——但它终将被摘下。',
  },
  // 日耳曼尼亚（最终目标）
  germania: {
    id: 'germania',
    name: '日耳曼尼亚',
    x: 60, y: 60,
    owner: 'germany',
    garrison: 3000,
    supplies: 1500,
    morale: 90,
    desc: '纳粹德国的「世界之都」。1971年的那场战争将终结「新秩序」——从这里开始，也在这里结束。',
  },
};

// 势力颜色（TNO 军阀 + 2WRW）
const Factions = {
  red: { name: '布里亚特ASSR（萨布林）', color: '#c03030', light: '#e06060' },
  nkvd: { name: '伊尔库茨克（亚戈达NKVD）', color: '#604060', light: '#806090' },
  japan: { name: '日本帝国（关东军）', color: '#b05050', light: '#d07070' },
  black: { name: '黑军 / 黑军团', color: '#303030', light: '#555555' },
  siberia: { name: '西伯利亚军阀', color: '#4070a0', light: '#6090c0' },
  feudal: { name: '封建公国', color: '#a08040', light: '#c0a060' },
  germany: { name: '纳粹德国', color: '#802020', light: '#a04040' },
};

// ===== 章节定义 =====
const Chapters = [
  {
    id: 0,
    title: '序章 · 新秩序的世界',
    subtitle: '1962年 · 欧亚大陆',
    defaultPov: null,
    description: '1924年布哈林胜出，1945年苏联崩溃，1962年纳粹登月。世界在黑暗中等待黎明——而在贝加尔湖畔，有人正在酝酿一场新的十月革命。',
  },
  {
    id: 1,
    title: '第一章 · 来自西边的故人',
    subtitle: '1962年冬 · 上乌金斯克',
    defaultPov: 'anna',
    description: '安娜·罗森塔尔娃在贝加尔湖东岸的上乌金斯克过着平静的地下工作生活。一个NKVD军官的出现打破了她试图遗忘的过去……',
  },
  {
    id: 2,
    title: '第二章 · 「国际」与「革命」',
    subtitle: '1962年冬 · 地下防空洞',
    defaultPov: 'sablin',
    description: '第一次代表大会召开了。瓦列里·萨布林登上讲台，讲出了那句振聋发聩的话——我们就再造红军，我们将再造苏维埃！',
  },
  {
    id: 3,
    title: '第三章 · 新十月革命',
    subtitle: '1962年 · 上乌金斯克广播塔',
    defaultPov: 'sablin',
    description: '革命的时机成熟了。萨布林率部占领广播塔，向全俄罗斯广播自由的理想——布里亚特自治苏维埃社会主义共和国成立！',
  },
  {
    id: 4,
    title: '第四章 · 冰湖的解放',
    subtitle: '1963年 · 伊尔库茨克',
    defaultPov: 'anna',
    description: '向亚戈达的老巢进军！布哈林主义者、布里亚特牧民、青年军官、争取平等的妇女——全体人民都在等待这一刻。',
  },
  {
    id: 5,
    title: '第五章 · 东方红',
    subtitle: '196X年 · 满洲里 - 新疆',
    defaultPov: 'lyupasha',
    description: '西北的中国共产党打响了总反攻。全世界的无产者正在觉醒——从贝加尔湖到黄河，红色的黎明同时升起。',
  },
  {
    id: 6,
    title: '第六章 · 再造苏联',
    subtitle: '1963-1971年 · 全俄罗斯',
    defaultPov: 'sablin',
    description: '从贝加尔湖到乌拉尔。赤塔的公国、鄂木斯克的黑军团、新西伯利亚的学者——俄罗斯将重新统一，苏维埃联盟将重建。',
  },
  {
    id: 7,
    title: '终章 · 第二次西俄战争',
    subtitle: '1971年 · 莫斯科 - 日耳曼尼亚',
    defaultPov: 'sablin',
    description: '1971年，俄罗斯复兴。向德国宣战——收复莫斯科，进军日耳曼尼亚。新秩序的黎明，将从旧秩序的废墟上升起。',
  },
];

// ===== 游戏初始状态 =====
function createInitialState() {
  return {
    currentChapter: 0,
    currentScene: 'prologue_01',
    currentPov: 'anna',
    dialogueIndex: 0,
    flags: {},
    quests: {
      active: ['q_tno_intro'],
      completed: [],
    },
    party: [
      { ...Characters.anna, hp: Characters.anna.stats.hp, mp: Characters.anna.stats.mp, level: 1, exp: 0 },
    ],
    resources: {
      troops: 300,
      supplies: 150,
      morale: 90,
      territory: 1,
    },
    strongholds: JSON.parse(JSON.stringify(Strongholds)),
    saveTime: null,
  };
}
